package org.cas.client.platform.cascontrol.commonmenu;

import org.cas.client.platform.cascontrol.menuaction.SAction;

/**
 * The Constants for Action Name indexs. 常量命名按照emo.resource.international.pim.MenuConstant中相应常量名前加ID_。 修改代码后请运行相应测试程序。
 */
public interface PIMActionName {
    // For File Menu-------------------------------------------------------------
    int ID_FILE_NEW = 0;
    int ID_FILE_OPEN = ID_FILE_NEW + 1;
    int ID_FILE_CLOSE = ID_FILE_NEW + 2;
    int ID_FILE_SAVE = ID_FILE_NEW + 3;
    int ID_FILE_SAVE_AS = ID_FILE_NEW + 4;
    int ID_FILE_SAVE_ATTACH = ID_FILE_NEW + 5;
    int ID_FILE_FOLDER = ID_FILE_NEW + 6;
    int ID_FILE_ARCHIVE = ID_FILE_NEW + 7;
    int ID_FILE_IMPORT_EXPORT = ID_FILE_NEW + 8;
    int ID_FILE_SET_PRINTOUT = ID_FILE_NEW + 9;
    int ID_FILE_PRINT_PREVIEW = ID_FILE_NEW + 10;
    int ID_FILE_PRINT = ID_FILE_NEW + 11;
    int ID_FILE_SEND = ID_FILE_NEW + 12;
    int ID_FILE_PROPERTIES = ID_FILE_NEW + 13;
    int ID_FILE_EXIT = ID_FILE_NEW + 14;

    // File -> New ==============================
    int ID_FILE_NEW_MESSAGES = ID_FILE_EXIT + 1;
    int ID_FILE_NEW_TEMPLATES = ID_FILE_EXIT + 2;
    int ID_FILE_NEW_APPOINTMENT = ID_FILE_EXIT + 3;
    int ID_FILE_NEW_MEETING = ID_FILE_EXIT + 4;
    int ID_FILE_NEW_TASK = ID_FILE_EXIT + 5;
    int ID_FILE_NEW_CONTACT = ID_FILE_EXIT + 6;
    int ID_FILE_NEW_JOURNAL = ID_FILE_EXIT + 7;
    int ID_FILE_NEW_LIST = ID_FILE_EXIT + 8;
    int ID_FILE_NEW_FOLDER = ID_FILE_EXIT + 9;
    int ID_FILE_FOLDER_RENAME = ID_FILE_EXIT + 10;

    // File -> Save Attachment ==============================
    int ID_FILE_SAVE_ATTACH_NAME = ID_FILE_FOLDER_RENAME + 1;
    int ID_FILE_SAVE_ATTACH_ALL = ID_FILE_FOLDER_RENAME + 2;

    // File -> Save Attachment ==============================
    int ID_FILE_FOLDER_COPY = ID_FILE_SAVE_ATTACH_ALL + 1;
    int ID_FILE_FOLDER_MOVE = ID_FILE_SAVE_ATTACH_ALL + 2;
    int ID_FILE_FOLDER_DEL = ID_FILE_SAVE_ATTACH_ALL + 3;
    int ID_FILE_FOLDER_EMPTY = ID_FILE_SAVE_ATTACH_ALL + 4;
    int ID_FILE_FOLDER_PROPERTIES = ID_FILE_SAVE_ATTACH_ALL + 5;

    // For Edit Menu-------------------------------------------------------------
    int ID_EDIT_UNDO = ID_FILE_FOLDER_PROPERTIES + 1;
    int ID_EDIT_REDO = ID_FILE_FOLDER_PROPERTIES + 2;
    int ID_EDIT_CUT = ID_FILE_FOLDER_PROPERTIES + 3;
    int ID_EDIT_COPY = ID_FILE_FOLDER_PROPERTIES + 4;
    int ID_EDIT_PASTE = ID_FILE_FOLDER_PROPERTIES + 5;
    int ID_EDIT_PASTE_SPECIAL = ID_FILE_FOLDER_PROPERTIES + 6;
    int ID_EDIT_CLEAR = ID_FILE_FOLDER_PROPERTIES + 7;
    int ID_EDIT_SELECT_ALL = ID_FILE_FOLDER_PROPERTIES + 8;
    int ID_EDIT_DEL = ID_FILE_FOLDER_PROPERTIES + 9;
    int ID_EDIT_FIND = ID_FILE_FOLDER_PROPERTIES + 10;
    int ID_EDIT_MOVE_TO_FOLDER = ID_FILE_FOLDER_PROPERTIES + 11;
    int ID_EDIT_COPY_TO_FOLDER = ID_FILE_FOLDER_PROPERTIES + 12;
    int ID_EDIT_MARK_AS_READ = ID_FILE_FOLDER_PROPERTIES + 13;
    int ID_EDIT_MARK_AS_UNREAD = ID_FILE_FOLDER_PROPERTIES + 14;
    int ID_EDIT_MARK_ALL = ID_FILE_FOLDER_PROPERTIES + 15;
    int ID_EDIT_REPETITION = ID_FILE_FOLDER_PROPERTIES + 16;
    int ID_EDIT_FOLLOW_UP = ID_FILE_FOLDER_PROPERTIES + 17;
    int ID_EDIT_CATEGORIES = ID_FILE_FOLDER_PROPERTIES + 18;

    // For View Menu-------------------------------------------------------------
    int ID_VIEW_CURRENT = ID_EDIT_CATEGORIES + 1;
    int ID_VIEW_GO = ID_EDIT_CATEGORIES + 2;
    int ID_VIEW_PREVIOUS = ID_EDIT_CATEGORIES + 3;
    int ID_VIEW_NEXT = ID_EDIT_CATEGORIES + 4;
    int ID_VIEW_PANE = ID_EDIT_CATEGORIES + 5;
    int ID_VIEW_BOOK = ID_EDIT_CATEGORIES + 6;
    int ID_VIEW_CIRCUM = ID_EDIT_CATEGORIES + 7;
    int ID_VIEW_PREVIEW = ID_EDIT_CATEGORIES + 8;
    int ID_VIEW_ENCODING = ID_EDIT_CATEGORIES + 9;
    int ID_VIEW_FONTSIZE = ID_EDIT_CATEGORIES + 10;
    int ID_VIEW_TOOLBARS = ID_EDIT_CATEGORIES + 11;
    int ID_VIEW_STATUS_BAR = ID_EDIT_CATEGORIES + 12;

    // view -> current view==============================
    int ID_VIEW_CURRENT_MESSAGES = ID_VIEW_STATUS_BAR + 1;
    int ID_VIEW_CURRENT_CALENDAR = ID_VIEW_STATUS_BAR + 2;
    int ID_VIEW_CURRENT_TASKS = ID_VIEW_STATUS_BAR + 3;
    int ID_VIEW_CURRENT_CONTACTS = ID_VIEW_STATUS_BAR + 4;
    int ID_VIEW_CURRENT_JOURNAL = ID_VIEW_STATUS_BAR + 5;
    int ID_VIEW_CURRENT_DEFINE_VIEW = ID_VIEW_STATUS_BAR + 6;

    // view -> current view -> message###############################
    int ID_VIEW_CURRENT_MESSAGES_MESSAGES = ID_VIEW_CURRENT_DEFINE_VIEW + 1;
    int ID_VIEW_CURRENT_MESSAGES_BY_FOLLOW_UP_FLAG = ID_VIEW_CURRENT_DEFINE_VIEW + 2;
    int ID_VIEW_CURRENT_MESSAGES_LAST_SEVEN_DAYS = ID_VIEW_CURRENT_DEFINE_VIEW + 3;
    int ID_VIEW_CURRENT_MESSAGES_FLAGGED_FOR_NEXT_SEVEN_DAYS = ID_VIEW_CURRENT_DEFINE_VIEW + 4;
    int ID_VIEW_CURRENT_MESSAGES_BY_CONVENSATION = ID_VIEW_CURRENT_DEFINE_VIEW + 5;
    int ID_VIEW_CURRENT_MESSAGES_BY_SENDER = ID_VIEW_CURRENT_DEFINE_VIEW + 6;
    int ID_VIEW_CURRENT_MESSAGES_UNREAD_MESSAGES = ID_VIEW_CURRENT_DEFINE_VIEW + 7;
    int ID_VIEW_CURRENT_MESSAGES_SENT_TO = ID_VIEW_CURRENT_DEFINE_VIEW + 8;

    // view -> current view -> calendar###############################
    int ID_VIEW_CURRENT_CALENDAR_DAY = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 1;
    int ID_VIEW_CURRENT_CALENDAR_WEEK = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 2;
    int ID_VIEW_CURRENT_CALENDAR_WORK_WEEK = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 3;
    int ID_VIEW_CURRENT_CALENDAR_MONTH = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 4;
    int ID_VIEW_CURRENT_CALENDAR_CURRENT_APPOINTMENTS = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 5;
    int ID_VIEW_CURRENT_CALENDAR_EVENTS = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 6;
    int ID_VIEW_CURRENT_CALENDAR_ANNUAL_EVENTS = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 7;
    int ID_VIEW_CURRENT_CALENDAR_REGULAR_APPOINTMENTS = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 8;
    int ID_VIEW_CURRENT_CALENDAR_CATEGORY = ID_VIEW_CURRENT_MESSAGES_SENT_TO + 9;

    // view -> current view -> tasks###############################
    int ID_VIEW_CURRENT_TASKS_SIMPLE_LIST = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 1;
    int ID_VIEW_CURRENT_TASKS_DETAILED_LIST = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 2;
    int ID_VIEW_CURRENT_TASKS_CURRENT_LIST = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 3;
    int ID_VIEW_CURRENT_TASKS_NEXT_SEVEN_DAYS = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 4;
    int ID_VIEW_CURRENT_TASKS_OVERDUE_TASKS = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 5;
    int ID_VIEW_CURRENT_TASKS_By_CATEGORY = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 6;
    int ID_VIEW_CURRENT_TASKS_ASSIGNMENT = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 7;
    int ID_VIEW_CURRENT_TASKS_BY_PERSON_IN_CHARGE = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 8;
    int ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS = ID_VIEW_CURRENT_CALENDAR_CATEGORY + 9;

    // view -> current view -> contact###############################
    int ID_VIEW_CURRENT_CONTACTS_CARD = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 1;
    int ID_VIEW_CURRENT_CONTACTS_DETAIL = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 2;
    int ID_VIEW_CURRENT_CONTACTS_PHONE = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 3;
    int ID_VIEW_CURRENT_CONTACTS_CATEGORY = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 4;
    int ID_VIEW_CURRENT_CONTACTS_COMPANY = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 5;
    int ID_VIEW_CURRENT_CONTACTS_LOCATION = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 6;
    int ID_VIEW_CURRENT_CONTACTS_FOLLOW_UP = ID_VIEW_CURRENT_TASKS_COMPLETED_TASKS + 7;

    // view -> current view -> journal###############################
    int ID_VIEW_CURRENT_JOURNAL_BY_CATEGORY = ID_VIEW_CURRENT_CONTACTS_FOLLOW_UP + 1;
    int ID_VIEW_CURRENT_JOURNAL_ITEM_LIST = ID_VIEW_CURRENT_CONTACTS_FOLLOW_UP + 2;
    int ID_VIEW_CURRENT_JOURNAL_WEEK = ID_VIEW_CURRENT_CONTACTS_FOLLOW_UP + 3;

    // view -> Go To==============================
    int ID_VIEW_GO_FOLDER = ID_VIEW_CURRENT_JOURNAL_WEEK + 1;
    int ID_VIEW_GO_PIM_TODAY = ID_VIEW_CURRENT_JOURNAL_WEEK + 2;
    int ID_VIEW_GO_INBOX = ID_VIEW_CURRENT_JOURNAL_WEEK + 3;
    int ID_VIEW_GO_CALENDAR = ID_VIEW_CURRENT_JOURNAL_WEEK + 4;
    int ID_VIEW_GO_TASKS = ID_VIEW_CURRENT_JOURNAL_WEEK + 5;
    int ID_VIEW_GO_CONTACTS = ID_VIEW_CURRENT_JOURNAL_WEEK + 6;
    int ID_VIEW_GO_JOURNALS = ID_VIEW_CURRENT_JOURNAL_WEEK + 7;
    int ID_VIEW_GO_GO_TO_TODAY = ID_VIEW_CURRENT_JOURNAL_WEEK + 8;
    int ID_VIEW_GO_GO_TO_DATE = ID_VIEW_CURRENT_JOURNAL_WEEK + 9;

    // view -> Previous==============================
    int ID_VIEW_PREVIOUS_ITEM = ID_VIEW_GO_GO_TO_DATE + 1;
    int ID_VIEW_PREVIOUS_UNREAD_ITEM = ID_VIEW_GO_GO_TO_DATE + 2;
    int ID_VIEW_PREVIOUS_ITEM_IN_CONVENSATION = ID_VIEW_GO_GO_TO_DATE + 3;
    int ID_VIEW_PREVIOUS_ITEM_FROM_SENDER = ID_VIEW_GO_GO_TO_DATE + 4;
    int ID_VIEW_PREVIOUS_HIGH_PRIORITY_MESSAGE = ID_VIEW_GO_GO_TO_DATE + 5;
    int ID_VIEW_PREVIOUS_FLAGGED_MESSAGE = ID_VIEW_GO_GO_TO_DATE + 6;
    int ID_VIEW_PREVIOUS_FIRST_ITEM_IN_FOLDER = ID_VIEW_GO_GO_TO_DATE + 7;
    int ID_VIEW_PREVIOUS_UNCOMPLETED_TASK = ID_VIEW_GO_GO_TO_DATE + 8;

    // view -> Next==============================
    int ID_VIEW_NEXT_ITEM = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 1;
    int ID_VIEW_NEXT_UNREAD_ITEM = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 2;
    int ID_VIEW_NEXT_ITEM_IN_CONVENSATION = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 3;
    int ID_VIEW_NEXT_ITEM_FROM_SENDER = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 4;
    int ID_VIEW_NEXT_HIGH_PRIORITY_MESSAGE = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 5;
    int ID_VIEW_NEXT_FLAGGED_MESSAGE = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 6;
    int ID_VIEW_NEXT_FIRST_ITEM_IN_FOLDER = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 7;
    int ID_VIEW_NEXT_UNCOMPLETED_TASK = ID_VIEW_PREVIOUS_UNCOMPLETED_TASK + 8;

    // view -> Font Size==============================
    int ID_VIEW_FONTSIZE_LARGEST = ID_VIEW_NEXT_UNCOMPLETED_TASK + 1;
    int ID_VIEW_FONTSIZE_LARGER = ID_VIEW_NEXT_UNCOMPLETED_TASK + 2;
    int ID_VIEW_FONTSIZE_MEDIUM = ID_VIEW_NEXT_UNCOMPLETED_TASK + 3;
    int ID_VIEW_FONTSIZE_SMALLER = ID_VIEW_NEXT_UNCOMPLETED_TASK + 4;
    int ID_VIEW_FONTSIZE_SMALLEST = ID_VIEW_NEXT_UNCOMPLETED_TASK + 5;

    // insert menu--------------------------------------------------------------
    int ID_INSERT_ATTACHMENTS = ID_VIEW_FONTSIZE_SMALLEST + 1;
    int ID_INSERT_ITEM = ID_VIEW_FONTSIZE_SMALLEST + 2;
    int ID_INSERT_SIGNATURE = ID_VIEW_FONTSIZE_SMALLEST + 3;
    int ID_INSERT_PICTURE = ID_VIEW_FONTSIZE_SMALLEST + 4;
    int ID_INSERT_VIDEOS_AUDOIS = ID_VIEW_FONTSIZE_SMALLEST + 5;
    int ID_INSERT_HYPERLINK = ID_VIEW_FONTSIZE_SMALLEST + 6;

    // Format menu--------------------------------------------------------------
    int ID_FORMAT_FONT = ID_INSERT_HYPERLINK + 1;
    int ID_FORMAT_STYLE = ID_INSERT_HYPERLINK + 2;
    int ID_FORMAT_PARAGRAPH = ID_INSERT_HYPERLINK + 3;
    int ID_FORMAT_BULLETS_AND_NUMBERING = ID_INSERT_HYPERLINK + 4;
    int ID_FORMAT_BACKGROUND = ID_INSERT_HYPERLINK + 5;
    int ID_FORMAT_PLAIN_TEXT = ID_INSERT_HYPERLINK + 6;
    int ID_FORMAT_HTML = ID_INSERT_HYPERLINK + 7;

    // Tools menu--------------------------------------------------------------
    int ID_TOOLS_SEND_RECEIVE = ID_FORMAT_HTML + 1;
    int ID_TOOLS_REMOUT_ADMIN = ID_FORMAT_HTML + 2;
    int ID_TOOLS_SPELLING = ID_FORMAT_HTML + 3;
    int ID_TOOLS_CHECK_NAMES = ID_FORMAT_HTML + 4;
    int ID_TOOLS_MAIL_MERGE = ID_FORMAT_HTML + 5;
    int ID_TOOLS_EXECUTIVE_BOARD_ROOM = ID_FORMAT_HTML + 6;
    int ID_TOOLS_RULES_WIZARD = ID_FORMAT_HTML + 7;
    int ID_TOOLS_JUNK_MAIL = ID_FORMAT_HTML + 8;
    int ID_TOOLS_REPLY_TO_SENDER = ID_FORMAT_HTML + 9;
    int ID_TOOLS_REPLY_TO_ALL = ID_FORMAT_HTML + 10;
    int ID_TOOLS_FORWARD = ID_FORMAT_HTML + 11;
    int ID_TOOLS_ACCOUNTS = ID_FORMAT_HTML + 12;
    int ID_TOOLS_OPTIONS = ID_FORMAT_HTML + 13;
    int ID_TOOLS_TELECENTRE = ID_FORMAT_HTML + 14;

    // tools -> Send/Receive==============================
    int ID_TOOLS_SEND_RECEIVE_SEND_RECEIVE_ALL = ID_TOOLS_OPTIONS + 1;
    int ID_TOOLS_SEND_RECEIVE_RECEIVE_ALL = ID_TOOLS_OPTIONS + 2;
    int ID_TOOLS_SEND_RECEIVE_SEND_ALL = ID_TOOLS_OPTIONS + 3;
    int ID_TOOLS_SEND_RECEIVE_ACCOUNTS_LIST = ID_TOOLS_OPTIONS + 4;

    // tools -> Junk Mail
    int ID_TOOLS_JUNK_MAIL_SENDER_LIST = ID_TOOLS_SEND_RECEIVE_ACCOUNTS_LIST + 1;
    int ID_TOOLS_JUNK_MAIL_ADULT_CONTENT = ID_TOOLS_SEND_RECEIVE_ACCOUNTS_LIST + 2;

    int ID_BAR_REPLY = ID_TOOLS_JUNK_MAIL_ADULT_CONTENT + 1;
    int ID_BAR_REPLY_TO_ALL = ID_BAR_REPLY + 1;
    int ID_BAR_FORWARD = ID_BAR_REPLY_TO_ALL + 1;
    int ID_BAR_RECEIVE_AND_SENDER = ID_BAR_FORWARD + 1;
    int ID_BAR_DAY_CALENDAR = ID_BAR_RECEIVE_AND_SENDER + 1;
    int ID_BAR_WEEK_CALENDAR = ID_BAR_DAY_CALENDAR + 1;
    int ID_BAR_MONTH_CALENDAR = ID_BAR_WEEK_CALENDAR + 1;
    int ID_BAR_CUT = ID_BAR_MONTH_CALENDAR + 1;
    int ID_BAR_COPY = ID_BAR_CUT + 1;
    int ID_BAR_PASTE = ID_BAR_COPY + 1;
    int ID_BAR_BOLD = ID_BAR_PASTE + 1;
    int ID_BAR_ITALIC = ID_BAR_BOLD + 1;
    int ID_BAR_UNDERLINE = ID_BAR_ITALIC + 1;
    int ID_BAR_LEFT = ID_BAR_UNDERLINE + 1;
    int ID_BAR_CENTER = ID_BAR_LEFT + 1;
    int ID_BAR_RIGHT = ID_BAR_CENTER + 1;

    int ACTION_SIZE = ID_BAR_RIGHT + 1;

    // The Action for main control to handle the actions.
    public static final SAction[] ACTIONS = new SAction[ACTION_SIZE];
}
